export const SELECT_CARD = 'SELECT_CARD';
export const DATA_FETCH_REQUEST = 'DATA_FETCH_REQUEST';
export const TOGGLE_SUCESS_MSG = 'TOGGLE_SUCESS_MSG';
export const SET_EMAIL_ERROR_MSG = 'SET_EMAIL_ERROR_MSG';
export const SET_SELECTED_TAB = 'SET_SELECTED_TAB';